import type { Metadata } from "next";
import "./globals.css";
import { ContextProviders } from "@/contexts/Providers";

export const metadata: Metadata = {
  title: "Danadinha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="flex justify-center">
      <body className="w-dvw max-w-[450px] bg-linear-to-b from-[#3B3B3B] to-[#717070] px-4 pt-14 text-gray-200">
        <ContextProviders>{children}</ContextProviders>
      </body>
    </html>
  );
}
